-- Clear existing FAQ embeddings generated by Kimi text-embedding-v1.
-- FaqEmbeddingInitializer will regenerate them using DashScope text-embedding-v3 on next startup.
UPDATE faq_doc SET embedding = NULL;
