-- Clear existing FAQ embeddings generated by DashScope text-embedding-v3.
-- FaqEmbeddingInitializer will regenerate them with text-embedding-v4 on next startup.
UPDATE faq_doc SET embedding = NULL;
